### ISSUE TITLE
Error in downloading large files that exceeds 2GB from ArchiveIt

### ISSUE THREAD

**Issue by aalsum** [cul/hrwa_manager#1]
When I download large files from ArchiveIt, it gives an error in calculating the MD5 hash. Because the file content is converted into byte array where the array size exceeds the Max int.

IOUtils.toByteArray(fis)

https://github.com/cul/hrwa_manager/blob/master/src/main/java/edu/columbia/ldpd/hrwa/tasks/DownloadArchiveFilesFromArchivitTask.java#L268

**Comment by elohanlon** [comment]
@aalsum Thanks for the bug report.  Although there are still a few loose ends to tie up, I've done a full rewrite of the hrwa_manager application and won't be updating this version anymore.  Here's the new one:  https://github.com/cul/new_hrwa_manager

In new_hrwa_manager, I've removed the Java-based archive file download task (due to large file size issues and slow performance) and created a separate bash script that manages downloads instead.  It's been working very well and has been easier to maintain.  You can find the bash script here:

https://github.com/cul/new_hrwa_manager/tree/master/src/main/bash/getarcs

That should serve as a better download alternative.

Once new_hrwa_manager is fully finished, I'll be officially deprecating this hrwa_manager GitHub repo.  It's outdated, was built on Java 6 and hasn't been adequately tested with Java 7 and later.  The new version is also faster, and uses Elasticsearch instead of MySQL as an intermediate data store for unpacked archive file data.

**Comment by aalsum** [comment]
@elo2112  Thanks for the clarification. It's a good initiative to update the hrwa_manager. 

For the related issue, I already fixed in our customized version of hrwa_manager. 
https://github.com/sul-dlss/hrwa_manager/commit/c301d2f7efc6cc57fb74bb311e75904bd0869dd5

**Comment by elohanlon** [comment]
Great, thanks.  I'll gladly to accept a pull request if you want to submit one.  No pressure either way though, since this project is outdated.
